name: ifridge
recipe: lamp
services:
  appserver:
    webroot: public
    xdebug: "debug,develop"
    type: php:7.4
    config:
      php: .vscode/php.ini
  myservice:
    type: phpmyadmin
    hosts:
      - database
